// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets foo from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');

/**
 * Creates a foo
 *
 * @param payload - The data to be used to create a foo
 * @param callback
 */
exports.create = function (payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's all foos
 *
 * @param callback
 */
exports.find = function (callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's a specific foo by the id
 *
 * @param id  - The id of the foo to get
 * @param callback
 */
exports.findById = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Updates a specific foo
 *
 * @param id      - The id of the foo to be updated
 * @param payload - The data to be updated
 * @param callback
 */
exports.update = function (id, payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Remove a specific foo
 *
 * @param id      - The id of the foo to be deleted
 * @param callback
 */
exports.remove = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * sleep x ms then return flow
 *
 * @param callback
 */
exports.sleepController = function(callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/* Add new methods above */
